Repository Inikoo-Ltd/aiku, pull requests merged in 2025-04, with the labels that each got.

#1572 Structured data
  app/Actions/Web/Webpage/UI/EditWebpage.php
  app/Actions/Web/Webpage/UpdateWebpage.php
  database/seeders/datasets/WebsiteDataStructure/Merchant_listing.json
  database/seeders/datasets/WebsiteDataStructure/Organisation.json
  database/seeders/datasets/WebsiteDataStructure/Product_snippet.json
  database/seeders/datasets/WebsiteDataStructure/Product_variant.json
  database/seeders/datasets/WebsiteDataStructure/Profile_page.json
  package-lock.json
  package.json
  resources/js/Components/Forms/Fields/GoogleSearch.vue
  resources/js/Components/Forms/Fields/StructureDataWebsite.vue
  resources/js/Composables/Listing/FieldFormList.ts
  resources/js/Pages/Grp/EditModel.vue
  resources/js/Pages/Iris/Home.vue
Labels: Manual Review Time 30-60 min

#1587 ImageCustomQxtension
  resources/css/Iris/editor.css
  resources/js/Components/Forms/Fields/BubleTextEditor/CustomResizeImage/CustomImageSetting.ts
  resources/js/Components/Forms/Fields/BubleTextEditor/EditorV2.vue
  resources/js/Composables/styles.ts
  resources/js/Pages/Grp/Org/Web/WebpageWorkshop.vue
  resources/js/Pages/Grp/Web/PreviewWebpageWorkshop.vue
Labels: Manual Review Time 30-60 min

#1578 get shipping zone for order
  app/Actions/Ordering/Order/GetShippingAmount.php
  app/Actions/Ordering/Order/GetShippingZone.php
  app/Actions/Ordering/ShippingZone/StoreShippingZone.php
  app/Models/Ordering/ShippingZone.php
  app/Models/Ordering/ShippingZoneSchema.php
Labels: Manual Review Time 10-20 min

#1593 1591 mobile setting workshop and imporve mobile view for iris
  resources/js/Components/CMS/Fields/Background.vue
  resources/js/Components/CMS/Fields/Border.vue
  resources/js/Components/CMS/Fields/Dimension.vue
  resources/js/Components/CMS/Fields/InputNumberCss.vue
  resources/js/Components/CMS/Fields/Margin.vue
  resources/js/Components/CMS/Fields/Padding.vue
  resources/js/Components/CMS/Fields/Shadow.vue
  resources/js/Components/CMS/Webpage/CTA/Blueprint.ts
  resources/js/Components/CMS/Webpage/CTA/CTAIris.vue
  resources/js/Components/CMS/Webpage/CTA/CTAWorkshop.vue
  resources/js/Components/ScreenView.vue
  resources/js/Components/Workshop/Properties/BackgroundProperty.vue
  resources/js/Components/Workshop/Properties/BorderProperty.vue
  resources/js/Components/Workshop/Properties/ColorProperty.vue
  resources/js/Components/Workshop/Properties/DimensionProperty.vue
  resources/js/Components/Workshop/Properties/InputNumberCssProperty.vue
  resources/js/Components/Workshop/Properties/PaddingMarginProperty.vue
  resources/js/Components/Workshop/Properties/TextProperty.vue
  resources/js/Components/Workshop/SideEditor/ChildFieldSideEditor.vue
  resources/js/Components/Workshop/SideEditor/ParentFieldSideEditor.vue
  resources/js/Components/Workshop/SideEditor/RenderFields.vue
  resources/js/Composables/SideEditorHelper.ts
  resources/js/Composables/styles.ts
  resources/js/Pages/Grp/Web/PreviewWebpageWorkshop.vue
  resources/js/Pages/Grp/Web/PreviewWorkshop.vue
  resources/js/Pages/Iris/Home.vue
Labels: Manual Review Time 1+ hours

#1610 isDoc invoice format
  app/Actions/Accounting/Invoice/ISDocInvoice.php
  app/Actions/Accounting/Invoice/RepairInvoiceMissingUuid.php
  app/Actions/Accounting/Invoice/StoreInvoice.php
  app/Actions/Accounting/Invoice/UI/ShowInvoice.php
  app/Actions/Accounting/Invoice/WithInvoicesExport.php
  app/Actions/SysAdmin/Organisation/UI/EditOrganisationSettings.php
  app/Actions/SysAdmin/Organisation/UpdateOrganisation.php
  app/Models/Accounting/Invoice.php
  composer.json
  composer.lock
  database/migrations/2025_04_15_081950_add_uuid_to_invoices_table.php
  doklad.isdoc
  doklad.isdoc:Zone.Identifier
  filename.isdoc
  resources/js/Pages/Grp/Org/Accounting/Invoice.vue
  routes/grp/web/org/accounting.php
Labels: Manual Review Time 1+ hours
