Repository Inikoo-Ltd/aiku, pull requests merged in 2025-03, with the labels that each got.

#1487 Add extra orders stat hydrator & migration
  app/Actions/Catalogue/Shop/Hydrators/ShopHydrateOrderHandling.php
  app/Actions/Ordering/Order/UI/IndexOrders.php
  app/Actions/Ordering/UI/ShowOrdersBacklog.php
  app/Actions/SysAdmin/Group/Hydrators/GroupHydrateOrderHandling.php
  app/Actions/SysAdmin/Organisation/Hydrators/OrganisationHydrateOrderHandling.php
  app/Actions/SysAdmin/Organisation/Hydrators/OrganisationHydrateOrders.php
  app/Actions/SysAdmin/Organisation/UI/ShowOrganisationDashboard.php
  app/Actions/UI/Dashboards/ShowGroupDashboard.php
  app/Enums/UI/Ordering/OrdersBacklogTabsEnum.php
  resources/js/Pages/Grp/Ordering/OrdersBacklog.vue
Labels: Manual Review Time 1+ hours

#1526 Redirect
  app/Actions/Web/Redirect/StoreRedirect.php
  app/Actions/Web/Redirect/UI/CreateRedirect.php
  app/Actions/Web/Redirect/UI/EditRedirect.php
  app/Actions/Web/Redirect/UI/IndexRedirects.php
  app/Actions/Web/Redirect/UI/ShowRedirect.php
  app/Actions/Web/Redirect/UpdateRedirect.php
  app/Actions/Web/Webpage/UI/ShowWebpage.php
  app/Actions/Web/Website/UI/ShowWebsite.php
  app/Enums/UI/Web/WebpageTabsEnum.php
  app/Enums/UI/Web/WebsiteTabsEnum.php
  app/Http/Resources/Web/RedirectsResource.php
  app/Rules/NoDomainString.php
  database/migrations/2025_03_12_063901_add_unique_constraint_to_redirects_table.php
  resources/js/Components/Tables/Grp/Org/Web/TableRedirects.vue
  resources/js/Pages/Grp/Org/Web/Redirect.vue
  resources/js/Pages/Grp/Org/Web/Webpage.vue
  resources/js/Pages/Grp/Org/Web/Website.vue
  routes/grp/web/models.php
  routes/grp/web/org/fulfilments/websites.php
  routes/grp/web/org/shops/websites.php
Labels: Manual Review Time 1+ hours

#1540 feat: add legacy password authorization for web users and refactor lo…
  app/Actions/CRM/WebUser/AuthoriseWebUserWithLegacyPassword.php
  app/Actions/CRM/WebUser/Retina/RetinaLogin.php
  app/Actions/CRM/WebUser/Retina/RetinaRegister.php
  app/Actions/Fulfilment/FulfilmentCustomer/Hydrators/FulfilmentCustomerHydrateStatus.php
  app/Actions/SysAdmin/UI/Auth/Login.php
  app/Actions/Traits/WithLogin.php
  app/Transfers/Aurora/FetchAuroraWebUser.php
  resources/js/Pages/Retina/Auth/RetinaLogin.vue
Labels: Manual Review Time 5-10 min

#1550 Fix mounted saving in Workshop webpage
  resources/js/Components/CMS/Fields/Background.vue
  resources/js/Components/CMS/Fields/Link.vue
  resources/js/Components/CMS/Fields/Margin.vue
  resources/js/Components/CMS/Fields/Padding.vue
  resources/js/Components/Workshop/Properties/BackgroundProperty.vue
  resources/js/Components/Workshop/SideEditor/ParentFieldSideEditor.vue
  resources/js/Components/Workshop/SiteSettings.vue
  resources/js/Components/Workshop/WebpageSideEditor.vue
Labels: Manual Review Time 20-30 min

#1556 Dropshipping
  app/Actions/Dropshipping/ShopifyUser/DeleteRetinaShopifyUser.php
  database/migrations/2025_03_12_100010__create_platform_has_clients_table.php
  resources/js/Layouts/Pupil/PupilLeftSideBar.vue
  resources/js/Layouts/Pupil/PupilTopbar.vue
  resources/js/Layouts/PupilRetina.vue
  resources/js/Layouts/Retina.vue
  resources/js/Layouts/Retina/RetinaLeftSideBar.vue
  resources/js/Layouts/Retina/RetinaTopBar.vue
Labels: Manual Review Time 5-10 min

#1484 Outbox subscriber
  app/Actions/CRM/Customer/RegisterCustomer.php
  app/Actions/Catalogue/Shop/Hydrators/ShopHydrateDispatchedEmails.php
  app/Actions/Comms/DispatchedEmail/StoreDispatchedEmail.php
  app/Actions/Comms/DispatchedEmail/UI/IndexDispatchedEmails.php
  app/Actions/Comms/Email/SendCustomerApprovedEmail.php
  app/Actions/Comms/Email/SendCustomerRejectEmail.php
  app/Actions/Comms/Email/SendCustomerWelcomeEmail.php
  app/Actions/Comms/Email/SendInvoiceEmailToCustomer.php
  app/Actions/Comms/Email/SendNewCustomerNotification.php
  app/Actions/Comms/Email/SendNewCustomerToSubcriberEmail.php
  app/Actions/Comms/Email/StoreEmail.php
  app/Actions/Comms/Outbox/UI/GetOutboxShowcase.php
  app/Actions/Comms/Outbox/UI/ShowOutbox.php
  app/Actions/Comms/Outbox/UpdateOutbox.php
  app/Actions/Comms/OutboxHasSubscribers/Json/GetOutboxUsers.php
  app/Actions/Comms/OutboxHasSubscribers/StoreManyOutboxHasSubscriber.php
  app/Actions/Comms/Traits/WithSendBulkEmails.php
  app/Actions/Fulfilment/FulfilmentCustomer/RegisterFulfilmentCustomer.php
  app/Actions/Helpers/Snapshot/StoreEmailSnapshot.php
  app/Actions/SysAdmin/Group/Hydrators/GroupHydrateDispatchedEmails.php
  app/Actions/SysAdmin/Group/Seeders/SeedEmailTemplates.php
  app/Actions/SysAdmin/Organisation/HydrateOrganisations.php
  app/Actions/SysAdmin/Organisation/Hydrators/OrganisationHydrateDispatchedEmails.php
  app/Actions/SysAdmin/Organisation/Seeders/SeedOrganisationOutboxes.php
  app/Actions/Traits/WithOutboxBuilder.php
  app/Actions/Web/Website/SeedWebsiteOutboxes.php
  app/Enums/Comms/Outbox/OutboxCodeEnum.php
  app/Enums/Comms/Outbox/OutboxMergeTagsEnum.php
  app/Enums/UI/Mail/OutboxTabsEnum.php
  app/Http/Resources/Mail/OutboxHasSubscribersResource.php
  app/Http/Resources/Mail/OutboxUsersResource.php
  app/Models/SysAdmin/Group.php
  app/Models/SysAdmin/Organisation.php
  database/migrations/2025_03_14_100000_add_indices_to_dispatched_emails_table.php
  database/seeders/datasets/email-templates/delivery_note_dispatched/delivery_note_dispatched.blade.php
  database/seeders/datasets/email-templates/delivery_note_undispatched/delivery_note_undispatched.blade.php
  database/seeders/datasets/email-templates/new_customer/new_customer.blade.php
  database/seeders/datasets/email-templates/new_order/new_order.blade.php
  resources/js/Components/DataDisplay/Dashboard/Widget/UserSubscribe.vue
  resources/js/Components/Showcases/Grp/OutboxShowcase.vue
  resources/js/Components/StoredItemsProperty.vue
  resources/js/Composables/Listing/DashboardWidgetsList.ts
  routes/grp/web/json.php
  routes/grp/web/models.php
Labels: Manual Review Time 1+ hours

#1554 Pallet data in pdf invoice
  app/Actions/Accounting/Invoice/InvoiceRecurringBillTransactions.php
  app/Actions/Accounting/Invoice/UI/ShowInvoice.php
  app/Actions/Accounting/Invoice/UI/ShowInvoiceDeleted.php
  app/Actions/Accounting/Invoice/WithInvoicesExport.php
  app/Actions/Accounting/InvoiceTransaction/ExportFulfilmentInvoiceTransactions.php
  app/Actions/Accounting/InvoiceTransaction/StoreInvoiceTransaction.php
  app/Actions/Accounting/InvoiceTransaction/UI/IndexItemizedInvoiceTransactions.php
  app/Actions/Accounting/StandaloneFulfilmentInvoice/UI/ShowStandaloneFulfilmentInvoiceInProcess.php
  app/Actions/Maintenance/Aurora/RepairFulfilmentInvoiceMissingPalletData.php
  app/Actions/Retina/Accounting/Invoice/Transaction/ExportRetinaFulfilmentInvoiceTransactions.php
  app/Actions/Retina/Billing/UI/ShowRetinaInvoice.php
  app/Enums/UI/Accounting/InvoiceTabsEnum.php
  app/Enums/UI/Accounting/StandaloneFulfilmentInvoiceTabsEnum.php
  app/Exports/Accounting/FulfilmentInvoiceTransactionsExport.php
  app/Http/Resources/Accounting/ItemizedInvoiceTransactionsResource.php
  app/Http/Resources/Accounting/StandaloneFulfilmentInvoiceTransactionsResource.php
  app/Models/Accounting/InvoiceTransaction.php
  resources/js/Components/Tables/Grp/Org/Accounting/TableItemizedTransactions.vue
  resources/js/Pages/Grp/Org/Accounting/Invoice.vue
  resources/js/Pages/Retina/Billing/RetinaInvoice.vue
  resources/js/Pages/Retina/Billing/RetinaTableItemizedTransactions.vue
  resources/views/invoices/templates/pdf/invoice.blade.php
  routes/retina/web/fulfilment/billing.php
Labels: Manual Review Time 1+ hours

#1564 Dropshipping
  app/Actions/Dropshipping/Shopify/Product/GetApiProductsFromShopify.php
  app/Actions/Dropshipping/Tiktok/Order/ShowTiktokOrderApi.php
  app/Actions/Dropshipping/Tiktok/Order/StoreTiktokOrder.php
  app/Actions/Dropshipping/Tiktok/Traits/WithTiktokApiServices.php
  app/Actions/Dropshipping/Tiktok/Webhooks/HandleOrderIncomingTiktok.php
  app/Actions/Retina/Dropshipping/Client/FetchRetinaCustomerClientFromShopify.php
  app/Actions/Retina/Dropshipping/Client/UI/IndexRetinaPlatformCustomerClients.php
  routes/grp/webhooks/webhooks.php
Labels: Manual Review Time 10-20 min

#1571 1557 -> Main
  app/Actions/UI/Iris/ShowHome.php
  app/Actions/Web/Webpage/GenerateWebpageSeoData.php
  app/Actions/Web/Webpage/StoreWebpage.php
  app/Actions/Web/Webpage/UI/CreateWebpage.php
  app/Actions/Web/Webpage/UI/EditWebpage.php
  app/Enums/Web/Webpage/WebpageSeoStructureTypeEnum.php
  app/Models/Web/Webpage.php
  database/migrations/2025_03_27_053826_add_columns_to_webpages_table.php
  resources/js/Components/Forms/Fields/WebsiteStructured/WebsiteStructured.vue
  resources/js/Components/Pure/PureInputWithAddOn.vue
  resources/js/Pages/Iris/Home.vue
Labels: Manual Review Time 30-60 min
