Repository Inikoo-Ltd/aiku, pull requests merged in 2025-07, with the labels that each got.

#1847 Settle Retina ORder with balance
  app/Actions/Accounting/OrderPaymentApiPoint/WebHooks/CheckoutComOrderPaymentSuccess.php
  app/Actions/Accounting/PaymentAccountShop/UI/GetRetinaPaymentAccountShopCheckoutComData.php
  app/Actions/Retina/Dropshipping/Checkout/UI/ShowRetinaDropshippingCheckout.php
  app/Actions/Retina/Dropshipping/Orders/SettleRetinaOrderWithBalance.php
Labels: Manual Review Time 10-20 min

#1854 unifnishged pay order with saved mit cards
  app/Actions/Retina/Dropshipping/Orders/PayRetinaOrderWithSavedCards.php
Labels: Manual Review Time 5-10 min

#1877 New Order email notification to customer for every channel
  app/Actions/Comms/Email/SendNewOrderToCustomerNotification.php
  app/Actions/Comms/Traits/WithSendBulkEmails.php
  app/Actions/Ordering/Order/SubmitOrder.php
  database/seeders/datasets/email-templates/new_order/new_order.blade.php
Labels: Manual Review Time 20-30 min

#1885 DS Adjust invoice data based on DN
  app/Actions/Ordering/Order/GenerateOrderInvoice.php
Labels: Manual Review Time 20-30 min

#1982 shopify webhook -> M
  resources/js/Components/Table/Table.vue
  resources/js/Components/Tables/Grp/Org/CRM/TablePortfoliosShopify.vue
  resources/js/Components/Tables/Retina/RetinaTablePortfoliosShopify.vue
  resources/js/Pages/Grp/Org/Dropshipping/Portfolios.vue
  resources/js/Pages/Retina/Dropshipping/Platform/PlatformDashboard.vue
  resources/js/Pages/Retina/Dropshipping/Portfolios.vue
Labels: Manual Review Time 5-10 min

#2013 Delete web user
  app/Actions/Analytics/WebUserRequest/UI/IndexWebUserRequests.php
  app/Actions/CRM/WebUser/DeleteWebUser.php
  app/Actions/CRM/WebUser/IndexWebUsersInCRM.php
  app/Actions/CRM/WebUser/ShowWebUser.php
  app/Actions/CRM/WebUser/WithAuthorizeWebUserScope.php
  app/Actions/Traits/Authorisations/WithCRMAuthorisation.php
  app/Actions/Traits/Authorisations/WithCRMEditAuthorisation.php
  app/Http/Resources/CRM/WebUserResource.php
  app/Http/Resources/CRM/WebUsersResource.php
  resources/js/Components/Tables/Grp/Org/CRM/TableWebUsers.vue
  resources/js/Pages/Grp/Org/Shop/CRM/WebUser.vue
  routes/grp/web/models.php
Labels: Manual Review Time 30-60 min
